# Generated by Django 2.1.7 on 2019-02-28 14:38

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('registration_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_login_datetime', models.DateTimeField(auto_now=True)),
                ('telephone_number', models.CharField(max_length=16)),
                ('personal_email', models.EmailField(max_length=254)),
                ('facebook_page', models.URLField()),
                ('major', models.CharField(choices=[('ING_INF_T', 'Ingegneria informatica triennale'), ('ING_INF_M', 'Ingegneria informatica magistrale'), ('ING_MEC_T', 'Ingegneria meccanica triennale'), ('ING_MEC_M', 'Ingegneria meccanica magistrale'), ('ING_GES_T', 'Ingegneria gestionale triennale'), ('ING_GES_M', 'Ingegneria gestionale magistrale')], max_length=10)),
                ('year_of_study', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('sold_books_number', models.IntegerField(default=0)),
                ('bought_books_number', models.IntegerField(default=0)),
                ('reports_number', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_class', models.CharField(choices=[('A', 'Classe A'), ('B', 'Classe B'), ('C', 'Classe C'), ('D', 'Classe D')], max_length=1)),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_edit_datetime', models.DateTimeField(auto_now=True)),
                ('purchase_confirmation', models.BooleanField()),
                ('buyer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('t', 'title'), ('tr', 'title_review'), ('ba', 'book_ad'), ('ur', 'user_review')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='InterestingTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('cover_image', models.ImageField(upload_to='images/title_covers')),
                ('description', models.TextField(max_length=500)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_edit_datetime', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('FIS', 'Fisica'), ('MAT', 'Matematica'), ('INF', 'Informatica'), ('MEC', 'Meccanica'), ('EN', 'Elettronica'), ('ECO', 'Economia'), ('AUT', 'Automazione'), ('STA', 'Statistica')], max_length=3)),
                ('content_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='titoli_content', to='sales.Content')),
                ('description_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descrizioni', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.BookAd')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interestingtitle',
            name='title_isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Title'),
        ),
        migrations.AddField(
            model_name='interestingtitle',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesting_titles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookad',
            name='content_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annunci_content', to='sales.Content'),
        ),
        migrations.AddField(
            model_name='bookad',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annunci_studente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookad',
            name='title_isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annunci_titolo', to='sales.Title'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('ad_id', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='interestingtitle',
            unique_together={('title_isbn', 'user_id')},
        ),
    ]
