# Generated by Django 2.1.7 on 2019-03-21 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190228_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisti', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendite', to=settings.AUTH_USER_MODEL)),
                ('title', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendite_titolo', to='sales.Title')),
            ],
        ),
        migrations.RenameField(
            model_name='bookad',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='bookad',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='bookad',
            name='purchase_confirmation',
        ),
        migrations.AddField(
            model_name='bookad',
            name='photo',
            field=models.ImageField(default='default-user.png', height_field=100, upload_to='books_photos', width_field=100),
        ),
    ]
