# Generated by Django 2.1.7 on 2019-03-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190321_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookad',
            name='photo',
        ),
    ]
